default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: band_app_development

test:
  <<: *default
  database: band_app_test

production:
  <<: *default
  database: band_app_production
  username: band_app
  password: <%= ENV['BAND_APP_DATABASE_PASSWORD'] %>